services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/app
    env_file: "./requirements/nginx/conf/nginx.env"
    stdin_open: true
    tty: true
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file: "./global.env"
    environment:
      MY_SQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MY_SQL_USER_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    stdin_open: true
    tty: true
    volumes:
      - mariadb_volume:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    env_file: "./global.env"
    volumes:
      - wordpress_volume:/app
    stdin_open: true
    tty: true

#mount sql database: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver16&pivots=cs1-bash#mount-a-host-directory-as-data-volume
#${PWD}: https://stackoverflow.com/questions/71680749/docker-failed-to-mount-local-volume-mount-no-such-file-or-directory
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/wp"
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/mariadb"

secrets:
  db_password:
    file: "../secrets/db_password.txt"
  db_root_password:
    file: "../secrets/db_root_password.txt"