services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/app
    networks:
      - inception
    env_file: 
      - "./global.env"
      - "./requirements/nginx/conf/nginx.env"
    restart: on-failure
    stdin_open: true
    tty: true
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: 
      - "./global.env"
      - "../secrets/db_password.env"
      - "../secrets/db_root_password.env"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
    stdin_open: true
    tty: true
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file: 
      - "./global.env"
      - "../secrets/db_password.env"
      - "../secrets/db_root_password.env"
      - "../secrets/wordpress_admin_acc.env"
    volumes:
      - wordpress_volume:/app
    networks:
      - inception
    restart: on-failure
    stdin_open: true
    tty: true

#mount sql database: https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver16&pivots=cs1-bash#mount-a-host-directory-as-data-volume
#${PWD}: https://stackoverflow.com/questions/71680749/docker-failed-to-mount-local-volume-mount-no-such-file-or-directory
volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/wp"
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/data/mariadb"

#https://docs.docker.com/compose/how-tos/networking/
networks:
  inception:
    driver: bridge